# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Question.create(question: "Would you rather fight 1 horse-sized duck, or 100 duck-sized horses?")
Question.create(question: "Which would you prefer — three wishes over five years or one wish right now?")
Question.create(question: "Would you rather be clever or beautiful?")
Question.create(question: "Would you rather be really hairy or bald?")
Question.create(question: "Would you like to be taller or thinner?")
Question.create(question: "Would you rather go to a tropical island or the Arctic")
Question.create(question: "Would you rather be hot or cold?")
Question.create(question: "Would you rather lock yourself out of your house or your car?")
Question.create(question: "Would you rather have true love or $1 million?")
Question.create(question: "Would you prefer to visit Earth in 2100 or travel back to 1900?")
Question.create(question: "Would you rather have a dog or a cat?")
Question.create(question: "Would you rather meet your ancestors or descendants?")
Question.create(question: "Would you rather have the ability to be invisible or to read minds?")
Question.create(question: "Would you rather be able to fly or breathe underwater?")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")
# Question.create(question: "")