# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Question.create(question: "Would you rather fight 1 horse-sized duck, or 100 duck-sized horses?")
# Question.create(question: "Which would you prefer — three wishes over five years or one wish right now?")
# Question.create(question: "Would you rather be clever or beautiful?")
# Question.create(question: "Would you rather be really hairy or bald?")
# Question.create(question: "Would you like to be taller or thinner?")
Question.create(question: "Would you rather go to a tropical island or the Arctic")
Question.create(question: "Would you rather be hot or cold?")
Question.create(question: "Would you rather lock yourself out of your house or your car?")
Question.create(question: "Would you rather have true love or $1 million?")
Question.create(question: "Would you prefer to visit Earth in 2100 or travel back to 1900?")
Question.create(question: "Would you rather have a dog or a cat?")
Question.create(question: "Would you rather meet your ancestors or descendants?")
Question.create(question: "Would you rather have the ability to be invisible or to read minds?")
Question.create(question: "Would you rather be able to fly or breathe underwater?")
Question.create(question: "Would you rather go on vacation to Europe or the Caribbean?")
Question.create(question: "Would you rather legally change your last name to Hitler, or never eat chocolate again?")
Question.create(question: "Would you rather have no internet, or no cell phone?")
Question.create(question: "Would you rather have no one show up to your funeral or wedding?")
Question.create(question: "Would you rather visit the doctor or the dentist?")
Question.create(question: "Would you rather eat broccoli or carrots?")
Question.create(question: "Would you rather be a giant rodent or a tiny elephant?")
Question.create(question: "Would you rather watch TV or listen to music?")
Question.create(question: "Would you rather own a lizard or a snake?")
Question.create(question: "Would you rather have a beach holiday or a mountain holiday?")
Question.create(question: "Would you rather be invisible or be able to read minds?")
Question.create(question: "Would you rather be hairy all over or completely bald?")
Question.create(question: "Would you rather be the most popular or the smartest person alive?")
Question.create(question: "Would you rather make headlines for saving somebody’s life or winning a Nobel Prize?")
Question.create(question: "Would you rather go without television or fast food for the rest of your life?")
Question.create(question: "Would you rather be attractive and dumb or be ugly and really smart?")
Question.create(question: "Would you rather always be cold or always be hot?")
Question.create(question: "Would you rather not hear or not see?")
Question.create(question: "Would you rather eliminate hunger and disease or be able to bring lasting world peace?")
Question.create(question: "Would you rather be stranded on a deserted island alone or with someone you don’t like?")
Question.create(question: "Would you rather see the future or change the past?")
Question.create(question: "Would you rather be three inches taller or three inches shorter?")
Question.create(question: "Would you rather wrestle a lion or fight a shark?")
Question.create(question: "Would you rather live under water and swim with the fish, or be able to travel through space and touch the stars?")
Question.create(question: "Would you rather have magical powers to save the world, or be the strongest person in the world?")
Question.create(question: "Would you rather have a dinosaur or a blue whale for a pet?")
Question.create(question: "Would you rather be blind or deaf?")
Question.create(question: "Would you rather have 500 spiders crawling in your house or 1000 crickets jumping around your room?")
Question.create(question: "Would you rather drink a glass full of liquid soap or eat 2 spoons of soap?")
Question.create(question: "Would you rather wot watch television or not eat fast food for a month?")
Question.create(question: "Would you rather attend school at Hogwarts or live in Narnia?")
Question.create(question: "Would you rather have many acquaintances and no friends, or have only one or two close friends?")
Question.create(question: "Would you rather win a million dollars in lottery or never have to pay for anything ever again?")
Question.create(question: "Would you rather fly all over the world with your favorite celebrity or be stuck on an island with the one you love?")
Question.create(question: "Would you rather become a popular celebrity whom everyone hates or be a normal person whom everyone loves?")
Question.create(question: "Would you rather go about your normal day naked or have smelly breath and body odor for the whole day?")
Question.create(question: "Would you rather kiss a jellyfish or step on a crab?")
Question.create(question: "Would you rather have a beautiful house and an ugly car or an ugly house and a beautiful car?")
Question.create(question: "Would you rather age from the neck up only or the neck down only?")
Question.create(question: "Would you rather eat anything and never get fat or read people’s mind?")
Question.create(question: "Would you rather do 10,000 jumping jacks without a break or do 2,000 sit-ups without a break")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
Question.create(question: "Would you rather ")
















