# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Question.create(question: "Would you rather fight 1 horse-sized duck, or 100 duck-sized horses?")
# Question.create(question: "Which would you prefer — three wishes over five years or one wish right now?")
# Question.create(question: "Would you rather be clever or beautiful?")
# Question.create(question: "Would you rather be really hairy or bald?")
# Question.create(question: "Would you like to be taller or thinner?")
Question.create(question: "Would you rather go to a tropical island or the Arctic")
Question.create(question: "Would you rather be hot or cold?")
Question.create(question: "Would you rather lock yourself out of your house or your car?")
Question.create(question: "Would you rather have true love or $1 million?")
Question.create(question: "Would you prefer to visit Earth in 2100 or travel back to 1900?")
Question.create(question: "Would you rather have a dog or a cat?")
Question.create(question: "Would you rather meet your ancestors or descendants?")
Question.create(question: "Would you rather have the ability to be invisible or to read minds?")
Question.create(question: "Would you rather be able to fly or breathe underwater?")
Question.create(question: "Would you rather go on vacation to Europe or the Caribbean?")
Question.create(question: "Would you rather legally change your last name to Hitler, or never eat chocolate again?")
Question.create(question: "Would you rather have no internet, or no cell phone?")
Question.create(question: "Would you rather have no one show up to your funeral or wedding?")
Question.create(question: "Would you rather visit the doctor or the dentist?")
Question.create(question: "Would you rather eat broccoli or carrots?")
Question.create(question: "Would you rather be a giant rodent or a tiny elephant?")
Question.create(question: "Would you rather watch TV or listen to music?")
Question.create(question: "Would you rather own a lizard or a snake?")
Question.create(question: "Would you rather have a beach holiday or a mountain holiday?")
Question.create(question: "Would you rather be invisible or be able to read minds?")
Question.create(question: "Would you rather be hairy all over or completely bald?")
Question.create(question: "Would you rather be the most popular or the smartest person alive?")
Question.create(question: "Would you rather make headlines for saving somebody’s life or winning a Nobel Prize?")
Question.create(question: "Would you rather go without television or fast food for the rest of your life?")
Question.create(question: "Would you rather be attractive and dumb or be ugly and really smart?")
Question.create(question: "Would you rather always be cold or always be hot?")
Question.create(question: "Would you rather not hear or not see?")
Question.create(question: "Would you rather eliminate hunger and disease or be able to bring lasting world peace?")
Question.create(question: "Would you rather be stranded on a deserted island alone or with someone you don’t like?")
Question.create(question: "Would you rather see the future or change the past?")
Question.create(question: "Would you rather be three inches taller or three inches shorter?")
Question.create(question: "Would you rather wrestle a lion or fight a shark?")
Question.create(question: "Would you rather live under water and swim with the fish, or be able to travel through space and touch the stars?")
Question.create(question: "Would you rather have magical powers to save the world, or be the strongest person in the world?")
Question.create(question: "Would you rather have a dinosaur or a blue whale for a pet?")
Question.create(question: "Would you rather be blind or deaf?")
Question.create(question: "Would you rather have 500 spiders crawling in your house or 1000 crickets jumping around your room?")
Question.create(question: "Would you rather drink a glass full of liquid soap or eat 2 spoons of soap?")
Question.create(question: "Would you rather wot watch television or not eat fast food for a month?")
Question.create(question: "Would you rather attend school at Hogwarts or live in Narnia?")
Question.create(question: "Would you rather have many acquaintances and no friends, or have only one or two close friends?")
Question.create(question: "Would you rather win a million dollars in lottery or never have to pay for anything ever again?")
Question.create(question: "Would you rather fly all over the world with your favorite celebrity or be stuck on an island with the one you love?")
Question.create(question: "Would you rather become a popular celebrity whom everyone hates or be a normal person whom everyone loves?")
Question.create(question: "Would you rather go about your normal day naked or have smelly breath and body odor for the whole day?")
Question.create(question: "Would you rather kiss a jellyfish or step on a crab?")
Question.create(question: "Would you rather have a beautiful house and an ugly car or an ugly house and a beautiful car?")
Question.create(question: "Would you rather age from the neck up only or the neck down only?")
Question.create(question: "Would you rather eat anything and never get fat or read people’s mind?")
Question.create(question: "Would you rather do 10,000 jumping jacks without a break or do 2,000 sit-ups without a break")
Question.create(question: "Would you rather would you rather always be 10 minutes late or always be 20 minutes early?")
Question.create(question: "Would you rather lose all of your money and valuables or all of the pictures you have ever taken?")
Question.create(question: "Would you rather your shirts be always two sizes too big or one size too small?")
Question.create(question: "Would you rather live in the wilderness far from civilization or live on the streets of a city as a homeless person?")
Question.create(question: "Would you rather live your entire life in a virtual reality where all your wishes are granted or in the real world?")
Question.create(question: "Would you rather be alone for the rest of your life or always be surrounded by annoying people?")
Question.create(question: "Would you rather never use social media sites / apps again or never watch another movie or TV show?")
Question.create(question: "Would you rather have an easy job working for someone else or work for yourself but work incredibly hard?")
Question.create(question: "Would you rather be the first person to explore a planet or be the inventor of a drug that cures a deadly disease?")
Question.create(question: "Would you rather have a horrible short term memory or a horrible long term memory?")
Question.create(question: "Would you rather be locked in a room that is constantly dark for a week or a room that is constantly bright for a week?")
Question.create(question: "Would you rather live without the internet or live without AC and heating?")
Question.create(question: "Would you rather have a horrible job, but be able to retire comfortably in 10 years or have your dream job, but have to work until the day you die?")
Question.create(question: "Would you rather be able to control fire or water?")
Question.create(question: "Would you rather have hands that kept growing as you got older or feet that kept growing as you got older?")
Question.create(question: "Would you rather unlimited sushi for life or unlimited tacos for life?")
Question.create(question: "Would you rather donate your body to science or donate your organs to people who need them?")
Question.create(question: "Would you rather never have to work again or never have to sleep again?")
Question.create(question: "Would you rather get one free round trip international plane ticket every year or be able to fly domestic anytime for free?")
Question.create(question: "Would you rather be fluent in all languages and never be able to travel or be able to travel anywhere for a year but never be able to learn a word of a different language?")
Question.create(question: "Would you rather have an unlimited international first class ticket or never have to pay for food at restaurants?")
Question.create(question: "Would you rather only eat meat, or only eat vegetables?")
Question.create(question: "Would you rather super sensitive taste or super sensitive hearing?")
Question.create(question: "Would you rather be able to type fast, or read fast?")
Question.create(question: "Would you rather have constantly dry eyes or a constant runny nose?")
Question.create(question: "Would you rather be a famous director or a famous actor?")
Question.create(question: "Would you rather be constantly tired no matter how much you sleep or constantly hungry no matter what you eat? ")
Question.create(question: "Would you rather have a completely automated home or a self-driving car?")
Question.create(question: "Would you rather be reincarnated as a fly or just cease to exist after you die?")
Question.create(question: "Would you rather be an amazing painter or a brilliant mathematician?")
Question.create(question: "Would you rather never lose your phone again or never lose your keys again?")
Question.create(question: "Would you rather never get angry or never be envious?")
Question.create(question: "Would you rather have free Wi-Fi wherever you go or be able to drink unlimited free coffee at any coffee shop?")
Question.create(question: "Would you rather lose your left hand or right foot?")
Question.create(question: "Would you rather have a flying carpet or a car that can drive underwater?")
Question.create(question: "Would you rather find five dollars on the ground or find all of your missing socks?")
Question.create(question: "Would you rather never be stuck in traffic again or never get another cold?")
Question.create(question: "Would you rather have a bottomless glass of wine or a bottomless gas tank?")
Question.create(question: "Would you rather go bald or always have terrible haircuts?")
Question.create(question: "Would you rather have no fingers or no elbows?")
Question.create(question: "Would you rather be forced to eat only spicy food or only really bland food?")
















